//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumer.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllAirline", ReplyAction="http://tempuri.org/IMyService/GetAllAirlineResponse")]
        WCFTest.Airline[] GetAllAirline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllAirline", ReplyAction="http://tempuri.org/IMyService/GetAllAirlineResponse")]
        System.Threading.Tasks.Task<WCFTest.Airline[]> GetAllAirlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/ConvertToString", ReplyAction="http://tempuri.org/IMyService/ConvertToStringResponse")]
        string ConvertToString(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/ConvertToString", ReplyAction="http://tempuri.org/IMyService/ConvertToStringResponse")]
        System.Threading.Tasks.Task<string> ConvertToStringAsync(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : Consumer.MyService.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<Consumer.MyService.IMyService>, Consumer.MyService.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFTest.Airline[] GetAllAirline() {
            return base.Channel.GetAllAirline();
        }
        
        public System.Threading.Tasks.Task<WCFTest.Airline[]> GetAllAirlineAsync() {
            return base.Channel.GetAllAirlineAsync();
        }
        
        public string ConvertToString(int number) {
            return base.Channel.ConvertToString(number);
        }
        
        public System.Threading.Tasks.Task<string> ConvertToStringAsync(int number) {
            return base.Channel.ConvertToStringAsync(number);
        }
    }
}
